//User table created

CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

//Sequence Created

create sequence user_seq 
start with 1
increment by 1
nocache;

//Password_reset_token Table Created

CREATE TABLE PASSWORD_RESET_TOKEN (
    TOKEN_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    RESET_TOKEN VARCHAR2(255) UNIQUE NOT NULL,
    EXPIRY_TIME TIMESTAMP NOT NULL,
    USED NUMBER(1) DEFAULT 0,

    CONSTRAINT FK_RESET_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
);

CREATE SEQUENCE RESET_TOKEN_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

drop table PASSWORD_RESET_TOKEN;
drop sequence RESET_TOKEN_SEQ;