spring.application.name=smart-performance-analyzer

server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jackson.serialization.write-dates-as-timestamps=false

huggingface.api-url=https://router.huggingface.co/v1/chat/completions
huggingface.model=openai/gpt-oss-120b:fastest
huggingface.token=${HF_TOKEN:}
huggingface.enabled=${HF_ENABLED:false}

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}